# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5413c1329e245ae17943cf58db0f82f1830dec0b88d3ae3e261ba012ec9eef80971a84747d0227b642f4da25a009b0d2bee26c97aefb895264488bb6d9a99ccf

test:
  secret_key_base: 79105a3be381313b18d32bbe1c37379d849663fe4f03efdeac2a68ffaacbe1f932727b6ed7e9adcf635356fd6ee6f3c17ea6c5f7e14d64909e58b3281f60bc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
